version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.:/tapioca-wrapper:cached
      - ../.pyenv-cache:/.pyenv:cached
    command: sleep infinity
