name: build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get -qq update && sudo apt-get -qq install python3-sphinx -y
      #     pip install --upgrade pip && pip install build twine
      # - name: Build docs
      #   run: make docs
      # - name: Build
      #   run: make dist
      - name: set up env
        run: echo "VERSION=$(eval 'python setup.py version')" >> $GITHUB_ENV
      - name: use env
        env:
          TAG: ${{ env.VERSION }}
        run: echo $TAG

  # tests:
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10", "3.11"]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip install "tox<4" tox-gh-actions
  #     - name: Test with tox
  #       env:
  #         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  #       run: tox
