name: release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      # - name: Create pypi config file
      #   run: sed 's,REPLACE_TOKEN,'"$PYPI_TOKEN"',' .pypirc.ini > .pypirc
      - name: Install dependencies
        run: pip install --upgrade pip && pip install build twine
      - name: Build
        run: make dist
      - name: Release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
      # - name: Release
      #   env:
      #     PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      #   run: |
      #     python setup.py sdist upload
      #     python setup.py bdist_wheel upload
      # - name: Remove pypi file
      #   run: rm .pypirc
